name = "Touchstone"
uuid = "58ad4722-9971-11e8-0794-397f0fb18c68"
authors = ["Michael Pichler <michael.pichler@meduniwien.ac.at>"]
version = "1.0.0"

[extras]
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
